"""Add User Table

Revision ID: 4d3b2c7df5e9
Revises: e2ac6b7e80e0
Create Date: 2024-12-16 16:11:16.674750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3b2c7df5e9'
down_revision = 'e2ac6b7e80e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.drop_table('user')
    # ### end Alembic commands ###
