"""Fixs issues whith Post and User

Revision ID: 8440bd438615
Revises: 9c41c0a5340b
Create Date: 2024-12-16 16:36:41.428944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8440bd438615'
down_revision = '9c41c0a5340b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_posts_user', 'user', ['user_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=100), server_default=sa.text("('')"), nullable=True))
        batch_op.drop_constraint('fk_posts_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
