"""add is_active, category, author

Revision ID: e2ac6b7e80e0
Revises: 3e3bf09697f2
Create Date: 2024-12-16 10:27:57.522184

"""
from alembic import op
import sqlalchemy as sa 
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = 'e2ac6b7e80e0'
down_revision = '3e3bf09697f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        if not has_column('posts', 'is_active'):
            batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True, server_default='default_category'))
        batch_op.add_column(sa.Column('author', sa.String(length=100), nullable=True, server_default=""))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('author')
        batch_op.drop_column('category')
        batch_op.drop_column('is_active')

def has_column(table_name, column_name):
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns

    # ### end Alembic commands ###

